version: '3.8'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
            - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
            - SPRING_DATASOURCE_USERNAME=sa
            - SPRING_DATASOURCE_PASSWORD=
            - SPRING_JPA_HIBERNATE_DDL-AUTO=update
            - SPRING_JPA_GENERATE-DDL=true
            - SPRING_JPA_SHOW-SQL=true
            - SPRING_FLIEWAY_ENABLED=true
            - SPRING_FLIEWAY_BASELINE-ON-MIGRATE=true
        command: ["java", "-jar", "/app/target/objective-0.0.1-SNAPSHOT.jar"]
        networks:
            - backend

networks:
    backend:
        driver: bridge